version: "3.7"
services:

  # database service
  mongo_db:
      image: mongo
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
